config/routes.rb
ConcertApp::Application.routes.draw do

  authenticated :admin_user do
    root :to => "home#index"
  end
  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    root to: "devise/sessions#new"
    put 'update_plan', :to => 'registrations#update_plan'
  end

  resources :users
  resources :artists
  resources :events
  resources :schedules

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :email, :price,
  	:tech_rider, :contract_rider, :poster, :picture, :w9, :resume

  has_many :events
  belongs_to :user

  scope :by_name, ->(name){ where("name like '%#{name}%'") }

  has_attached_file :poster, :styles => { :medium => "300x300>", mini: "120x120>", tiny: "50x50" }, 
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    default_url: "/assets/missing.jpg", 
    path: "upload/:class/:attachment/:style/:filename"

  has_attached_file :picture, :styles => { :medium => "300x300>", mini: "120x120>", tiny: "50x50" }, 
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    default_url: "/assets/missing.jpg", 
    path: "upload/:class/:attachment/:style/:filename"

  has_attached_file :tech_rider, 
  	storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    path: ":rails_root/public/upload/:class/:attachment/:style/:filename",
  	url: "/upload/:class/:attachment/:style/:filename"

	has_attached_file :contract_rider, 
  	storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    path: ":rails_root/public/upload/:class/:attachment/:style/:filename",
  	url: "/upload/:class/:attachment/:style/:filename"

  has_attached_file :w9, 
  	storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    path: ":rails_root/public/upload/:class/:attachment/:style/:filename",
  	url: "/upload/:class/:attachment/:style/:filename"

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_filter :authenticate_user!

	def index
		if params[:query].nil?
			@artists = Artist.paginate(page: params[:page], per_page: 10)
		else
			@artists = Artist.by_name(params[:query]).paginate(page: params[:page], per_page: 10)
		end
	end

	def show
		@artist = Artist.find(params[:id])
		@events = @artist.events.paginate(page: params[:page], per_page: 10)
	end

	def edit
		@artist = Artist.find(params[:id])
	end

	def new
		@artist = Artist.new
	end

	def create
		artist = Artist.new(params[:artist])
		artist.user_id = current_user.id
    if artist.save
      redirect_to(artists_path, notice: "New artist is successfully created.")
    else
      redirect_to(artists_path, notice: "Failed to create new artist.")
    end
	end

	def destroy
		artist = Artist.find(params[:id])
		if artist.destroy
			redirect_to(artists_path, notice: "The Artist is deleted successfully")
		else
			redirect_to(artists_path, notice: "Failed to delete the artist")
		end
	end

	def update
		artist = Artist.find(params[:id])
		if artist.update_attributes(params[:artist])
			redirect_to(artists_path, notice: "Your artist is updated successfully")
		else
			redirect_to(artists_path, notice: "Failed to update the event")
		end
	end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_create.html.haml
#add-artist.modal.fade{role: "dialog"}
  = simple_form_for :artist, url: artists_path, :html => {:method => :post, :multipart => true, :class => 'form-horizontal' } do |f|
    .modal-dialog
      .modal-content
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h4 Add Artist
        .modal-body
          .form-group
            = f.label :name, class: "col-sm-3"
            .col-sm-8
              = f.input_field :name, class: "form-control"
          .form-group
            = f.label :email, class: "col-sm-3"
            .col-sm-8
              = f.input_field :email, class: "form-control"
          .form-group
            = f.label :price, class: "col-sm-3"
            .col-sm-8
              = f.input_field :price, class: "form-control"

          .form-group
            = f.label :tech_rider, class: "col-sm-3"
            .col-sm-8
              = f.file_field :tech_rider, class: "form-control"
          .form-group
            = f.label :contract_rider, class: "col-sm-3"
            .col-sm-8
              = f.file_field :contract_rider, class: "form-control"
          .form-group
            = f.label :poster, class: "col-sm-3"
            .col-sm-8
              = f.file_field :poster, class: "form-control"

          .form-group
            = f.label :picture, class: "col-sm-3"
            .col-sm-8
              = f.file_field :picture, class: "form-control"

          .form-group
            = f.label :w9, class: "col-sm-3"
            .col-sm-8
              = f.file_field :w9, class: "form-control"
          .form-group
            = f.label :resume, class: "col-sm-3"
            .col-sm-8
              = f.file_field :resume, class: "form-control"

        .modal-footer
          = f.submit "Create", :class => "btn btn-primary"
          %a.btn.btn-default{"data-dismiss" => "modal", href: "#"} Cancel

app/views/artists/_modify.html.haml
.modal.fade{ role: "dialog", id: "artist-" + artist.id.to_s }
  = simple_form_for artist, url: artist_path(artist), :html => {:method => :put, :multipart => true, :class => 'form-horizontal' } do |f|
    .modal-dialog
      .modal-content
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h4 Edit Artist
        .modal-body
          .form-group
            = f.label :name, class: "col-sm-3"
            .col-sm-8
              = f.input_field :name, class: "form-control"
          .form-group
            = f.label :email, class: "col-sm-3"
            .col-sm-8
              = f.input_field :email, class: "form-control"
          .form-group
            = f.label :price, class: "col-sm-3"
            .col-sm-8
              = f.input_field :price, class: "form-control"

          .form-group
            = f.label :tech_rider, class: "col-sm-3"
            .col-sm-8
              = f.file_field :tech_rider, class: "form-control"
          .form-group
            = f.label :contract_rider, class: "col-sm-3"
            .col-sm-8
              = f.file_field :contract_rider, class: "form-control"
          .form-group
            = f.label :poster, class: "col-sm-3"
            .col-sm-8
              = f.file_field :poster, class: "form-control"

          .form-group
            = f.label :picture, class: "col-sm-3"
            .col-sm-8
              = f.file_field :picture, class: "form-control"

          .form-group
            = f.label :w9, class: "col-sm-3"
            .col-sm-8
              = f.file_field :w9, class: "form-control"
          .form-group
            = f.label :resume, class: "col-sm-3"
            .col-sm-8
              = f.file_field :resume, class: "form-control"

        .modal-footer
          = f.submit "Update", :class => "btn btn-primary"
          %a.btn.btn-default{"data-dismiss" => "modal", href: "#"} Cancel

app/views/artists/index.html.haml
.widget.stacked
  .widget-header
    %h3
      Artists
  .widget-content.min-height-200
    .img-thumbnail.col-md-12
      .col-md-6.text-right.pull-right
        = form_for :artist, url: artists_path, html: { method: :get, class: "form-inline" } do |f|
          .col-md-6
            .input-group
              %input.form-control{name: "query", value: "#{params[:query]}", type: "text", placeholder: "Artist Name"}
              %span.input-group-btn
                %button.btn.btn-default{type: "submit"} Search
          .col-md-6
            = link_to "New Artist", "#add-artist", class: "btn btn-primary", data: { toggle: "modal" }
      = render partial: "create"

    .table-responsive
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th Name
            %th Email
            %th Pricing
            %th Registered Date
            %th.action-field
        %tbody
          - @artists.each do |artist|
            %tr
              %td
                = link_to artist.name, artist_path(artist)
              %td
                = artist.email
              %td
                $
                = artist.price
              %td
                = artist.created_at.to_date
              %td
                = link_to "<i class='icon-edit'></i> Edit".html_safe, "#artist-#{artist.id}", class: "btn btn-default btn-sm", data: { toggle: "modal" }
                = render partial: "modify", locals: {artist: artist}
                = link_to "<i class='icon-remove'></i> Remove".html_safe, artist_path(artist), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-default btn-sm"
      = will_paginate @artists, previous_label: "&laquo;", next_label: "&raquo;"

app/views/artists/show.html.haml
.widget.stacked
  .widget-header
    %h3
      Event Detail
  .widget-content
    .clearfix{style: "line-height: 32px;"}
      .col-md-6.col-sm-12
        .col-sm-4
          %strong Name
        .col-sm-8
          = @artist.name
      
        .col-sm-4
          %strong Price
        .col-sm-8
          = @artist.price

        .col-sm-4
          %strong Picture
        .col-sm-8
          = image_tag @artist.picture.url(:medium), class: "img-thumbnail"

        .col-sm-4
          %strong Poster
        .col-sm-8
          = image_tag @artist.poster.url(:medium), class: "img-thumbnail"

      .col-md-6.col-sm-12

        .col-sm-4
          %strong Tech Rider
        .col-sm-8
          = link_to @artist.tech_rider_file_name, @artist.tech_rider.url

        .col-sm-4
          %strong Contract Rider
        .col-sm-8
          = link_to @artist.contract_rider_file_name, @artist.contract_rider.url

        .col-sm-4
          %strong W9
        .col-sm-8
          = link_to @artist.w9_file_name, @artist.w9.url

        .col-sm-4
          %strong Resume
        .col-sm-8
          = @artist.resume
    %hr
    %h4 Events
    .table-responsive
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th #
            %th Date
            %th Show Time
            %th School
            %th Artist
            %th Status
            %th Contact Sent?
        %tbody
          - @events.each do |event|
            %tr
              %td
                = link_to event.id, event_path(event)
              %td
                = event.created_at.to_date
              %td
                = event.show_time
              %td
                = event.school_name
              %td
                = event.artist.name
              %td
                = event.status
              %td

      = will_paginate @events, previous_label: "&laquo;", next_label: "&raquo;"


    .col-md-12.text-right
      %a.btn.btn-default{onclick: "history.back();"} Back