config/routes.rb
ConcertApp::Application.routes.draw do

  authenticated :admin_user do
    root :to => "home#index"
  end
  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    root to: "devise/sessions#new"
    put 'update_plan', :to => 'registrations#update_plan'
  end

  resources :users
  resources :artists
  resources :events
  resources :schedules

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	
	def index
		if params[:artist].nil? || params[:artist] == ""
			@events = Event.where({school_email: current_user.email})
						.paginate(page: params[:page], per_page: 10)
		else
			@events = Event.by_artist(params[:artist]).where({school_email: current_user.email})
						.paginate(page: params[:page], per_page: 10)
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		event = Event.find(params[:id])
		puts "#{event.performance_date} #{params[:show_time]}"
		performance_time = DateTime.strptime("#{event.performance_date} #{params[:event][:show_time]}", "%F %H:%M")

		event.performance_time = performance_time unless event.nil?
		if event.update_attributes(params[:event])
			redirect_to(schedules_path, notice: "You scheduled the event successfully")
		else
			redirect_to(schedules_path, notice: "Failed to schedule event")
		end
	end
end

app/views/schedules/edit.html.haml
.widget.stacked
  .widget-header
    %h3
      Schedule Event
  .widget-content
    = simple_form_for @event, url: schedule_path(@event), :html => { :method => :put, :class => 'form-horizontal' } do |f|
      .clearfix
        .col-md-4.col-sm-12
          .form-group
            = f.label :show_time, "Show Time", class: "col-sm-4"
            .input-group.bootstrap-timepicker.col-sm-8.input-append
              = f.input_field :show_time, class: "form-control timepicker"
              %span.input-group-addon.add-on
                %i.icon-time
          .form-group
            = f.label :time_zone, "Time Zone", class: "col-sm-4"
            .col-sm-8
              = f.input :time_zone, label: false, input_html: { class: "form-control" }

          .form-group
            = f.label :load_time, "Load In Time", class: "col-sm-4"
            .input-group.bootstrap-timepicker.col-sm-8.input-append
              = f.input_field :load_time, class: "form-control timepicker"
              %span.input-group-addon.add-on
                %i.icon-time
          
          .form-group
            = f.label :load_address, "Load In Address", class: "col-sm-4"
            .col-sm-8
              = f.input_field :load_address, class: "form-control"
          .form-group
            = f.label :contact_name, "Contact Name", class: "col-sm-4"
            .col-sm-8
              = f.input_field :contact_name, class: "form-control"
          .form-group
            = f.label :contact_phone, "Contact Phone No", class: "col-sm-4"
            .col-sm-8
              = f.input_field :contact_phone, class: "form-control input-phone"

        .col-md-4.col-sm-12
          .form-group
            = f.label :hotel_name, "Hotel Name", class: "col-sm-4"
            .col-sm-8
              = f.input_field :hotel_name, class: "form-control"
          .form-group
            = f.label :hotel_address, "Hotel Address", class: "col-sm-4"
            .col-sm-8
              = f.input_field :hotel_address, class: "form-control"
          .form-group
            = f.label :backup_content, "Backup Content", class: "col-sm-4"
            .col-sm-8
              = f.input_field :backup_content, class: "form-control"
          .form-group
            = f.label :backup_phone, "Backup Phone No", class: "col-sm-4"
            .col-sm-8
              = f.input_field :backup_phone, class: "form-control input-phone"

        .col-md-4.col-sm-12
          .checkbox
            %label
              = f.input_field :contract_signed, label: false
              Contract Signed
          .checkbox
            %label
              = f.input_field :payment_sent
              Payment Sent
          .checkbox
            %label
              = f.input_field :show_review_complete, label: false
              Show Review Complete
      .col-md-12.text-right
        = f.submit "Update", :class => "btn btn-primary"
        %a.btn.btn-default{onclick: "history.back();"} Cancel

app/views/schedules/index.html.haml
.widget.stacked
  .widget-header
    %h3
      Events
  .widget-content.min-height-200
    .img-thumbnail.col-xs-12
      = form_for :schedule, url: schedules_path, html: { method: :get, class: "form-inline"} do |f|
        .row
          .col-xs-12.col-sm-8.pull-right
            .col-xs-4.text-right{style: "margin-top: 5px;"}
              = label_tag :artist, "Artist"
            .col-xs-4
              = select_tag :artist, options_from_collection_for_select(Artist.all, "id", "name", params[:artist]), { :prompt => "View All", class: "form-control" }
            .col-xs-4
              %button.btn.btn-default{type: "submit"} Search

    .table-responsive
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th Date
            %th Show Time
            %th School
            %th Artist
            %th Status
            %th Contact Sent?
            %th
        %tbody
          - @events.each do |event|
            %tr
              %td
                = event.created_at.to_date
              %td
                = event.show_time
              %td
                = event.school_name
              %td
                = event.artist.name
              %td
                = event.status
              %td
                - if event.contract_file_name.nil?
                  Not Sent
                - else
                  = link_to "Sent", event.contract.url
              %td
                = link_to "<i class='icon-calendar'></i> Schedule".html_safe, edit_schedule_path(event), class: "btn btn-default btn-sm"
      = will_paginate @events, previous_label: "&laquo;", next_label: "&raquo;"